### ISSUE TITLE
请问能像gpt-2那样指定topk，生成不一样的结果吗

### ISSUE THREAD

**Issue by Pzeyang** [Icelame-31/news_title_summary_generate#1]

**Comment by Pzeyang** [comment]
如果可以，怎么添加参数，才可以对于同个输入生成不同的句子呢

**Comment by Icelame-31** [comment]
目前我测试着，对于相同的输入，只能得到相同的输出结果

**Comment by Pzeyang** [comment]
是，我测试也这样，不清楚这里生成代码是否可以指定
model.generate(max_length=200,
                                           eos_token_id=tokenizer.sep_token_id,
                                           decoder_start_token_id=tokenizer.cls_token_id,
                                           **input)

**Comment by Icelame-31** [comment]
具体的你可以尝试一下，关于这些参数的细节，我也不太了解

**Comment by Pzeyang** [comment]
好的谢谢
